// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRestAPI.Models;

namespace StudentRestAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240401174959_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentRestAPI.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmenId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(2001, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmenId = 1,
                            Email = "dangduc01@gmail.com",
                            FirstName = "Dang01",
                            Gender = 0,
                            LastName = "Duc01",
                            PhotoPath = "Images/01.png"
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(2001, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmenId = 4,
                            Email = "dangduc02@gmail.com",
                            FirstName = "Dang02",
                            Gender = 0,
                            LastName = "Duc02",
                            PhotoPath = "Images/02.png"
                        },
                        new
                        {
                            StudentId = 3,
                            DateOfBirth = new DateTime(2001, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmenId = 2,
                            Email = "dangduc03@gmail.com",
                            FirstName = "Dang03",
                            Gender = 1,
                            LastName = "Duc03",
                            PhotoPath = "Images/03.png"
                        },
                        new
                        {
                            StudentId = 4,
                            DateOfBirth = new DateTime(2001, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmenId = 3,
                            Email = "dangduc02@gmail.com",
                            FirstName = "Dang04",
                            Gender = 1,
                            LastName = "Duc04",
                            PhotoPath = "Images/04.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
